config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, except: %i[index show]
  resources :forests do
    resources :forest_reviews, only: %i[new create]
    resources :bookings, only: %i[new create update destroy index show]
    collection do
      get :index_owner
    end
  end
end

app/views/shared/_chat.html.erb
<div class="container-messages">
	<div class="d-flex no-gutters container-all-app">
	  <div class="col-md-4 chat-left">
      <div class="settings-tray">
        <img class="profile-image" src="https://www.clarity-enhanced.net/wp-content/uploads/2020/06/filip.jpg" alt="Profile img">
        <span class="settings-tray--right">
        <i class="fas fa-sync-alt"></i>
        <i class="fas fa-comment"></i>
        <i class="fas fa-bars"></i>
        </span>
      </div>
      <div class="search-box">
        <div class="input-wrapper">
        <i class="fas fa-search"></i>
        <input placeholder="Search here" type="text">
        </div>
      </div>
      <div class="friend-drawer friend-drawer--onhover">
        <img class="profile-image" src="https://www.clarity-enhanced.net/wp-content/uploads/2020/06/robocop.jpg" alt="">
        <div class="text">
        <h6>Robo Cop</h6>
        <p class="text-muted">Hey, you're arrested!</p>
        </div>
        <span class="time text-muted small">13:21</span>
      </div>
      <hr>
      <div class="friend-drawer friend-drawer--onhover">
        <img class="profile-image" src="https://www.clarity-enhanced.net/wp-content/uploads/2020/06/optimus-prime.jpeg" alt="">
        <div class="text">
        <h6>Optimus</h6>
        <p class="text-muted">Wanna grab a beer?</p>
        </div>
        <span class="time text-muted small">00:32</span>
      </div>
      <hr>
      <div class="friend-drawer friend-drawer--onhover ">
        <img class="profile-image" src="https://www.clarity-enhanced.net/wp-content/uploads/2020/06/real-terminator.png" alt="">
        <div class="text">
        <h6>Skynet</h6>
        <p class="text-muted">Seen that canned piece of s?</p>
        </div>
        <span class="time text-muted small">13:21</span>
      </div>
	  </div>

	  <div class="col-md-8 chat-right">
      <div class="settings-tray">
        <div class="friend-drawer no-gutters friend-drawer--grey active">
          <img class="profile-image" src="https://www.clarity-enhanced.net/wp-content/uploads/2020/06/robocop.jpg" alt="">
          <div class="text">
            <h6>Robo Cop</h6>
            <p class="text-muted">Layin' down the law since like before Christ...</p>
          </div>
          <span class="settings-tray--right">
            <i class="fas fa-sync-alt"></i>
            <i class="fas fa-comment"></i>
            <i class="fas fa-bars"></i>
          </span>
        </div>
      </div>
      <div class="chat-panel">
        <div class="row no-gutters">
          <div class="col-md-3">
            <div class="chat-bubble chat-bubble--left">
            Hello dude!
            </div>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-md-3 offset-md-9">
            <div class="chat-bubble chat-bubble--right">
            Hello dude!
            </div>
          </div>
        </div>
        <div class="row-barre-envoi">
          <div class="col-12">
            <div class="chat-box-tray">
            <i class="far fa-smile"></i>
            <input type="text" placeholder="Type your message here...">
            <i class="fas fa-microphone"></i>
            <i class="fas fa-paper-plane"></i>
            </div>
          </div>
        </div>
      </div>
	  </div>
	</div>
</div>

app/views/shared/_flashes.html.erb
<% if flash[:alert].present? %>
    <div class="flash flash-danger alert alert-dismissible fade show"><%=flash.alert%>
      <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
      </a>
</div>
<% elsif flash[:success].present? %>
    <div class="flash flash-success alert alert-dismissible fade show"><%=flash[:success]%>
      <a data-bs-dismiss="alert" aria-label="Close">
        <i class="fas fa-times"></i>
      </a>
</div>
<% end %>

<script>
  setTimeout(() => {
    const box = document.querySelector('.flash-success');
    box.style.display = 'none';
  }, 2500);
</script>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made by Chloé, Thomas, Kevin & Jules with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_modal_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="modal-flash">
    <%= msg %>
  </div>
<% end %>

<script>
  setTimeout(() => {
    const box = document.querySelector('.modal-flash');
    box.style.display = 'none';
  }, 2000);
</script>

app/views/shared/_navbar.html.erb
<div class="navbar-pages">
  <div class="navbar p-3">
    <div id="logo">
      <%= link_to '/', data: { turbolinks: 'false' } do %>
        <%= image_tag 'logo.png', width: 50%>
      <% end %>
    </div>


    <div class="login-avatar">
      <% if user_signed_in? %>
        <div class="dropdown-toggle d-flex" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-controller="toggle-dropdown" data-action="click->toggle-dropdown#toggle">
            <div class="ligne"></div>
          <% if current_user.photo.key %>
            <%= cl_image_tag current_user.photo.key, crop: :fill, class: 'avatar' %>
          <% else %>
            <%= image_tag 'gnome-avatar.jpg', class: 'avatar' %>
          <% end %>
        </div>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <div id="test">
            <%= link_to "Dashboard", index_owner_forests_path, class: "dropdown-item" %>
            <%= link_to "Add a Forest", '/forests/new', class: "dropdown-item" %>
            <%= link_to "Settings", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
      <% else %>
          <%= link_to "Login", new_user_session_path, class: "nav-link nav-login" %>
      <% end %>
    </div>
  </div>

  <div class='search-bar'>
    <div class="input-bar">
      <%= form_tag forests_path, method: :get do %>
        <%= text_field_tag :query, params[:query], placeholder:"Find your next forestreep", class: ''%>
    </div>
    <div class="loupe">
    <button type='submit'>
    <%#= submit_tag "Search", class: "btn btn-primary" %>
      <i class="fas fa-search"></i>
    </button>
    </div>
      <% end %>
  </div>


</div>