config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, except: %i[index show]
  resources :forests do
    resources :forest_reviews, only: %i[new create]
    resources :bookings, only: %i[new create update destroy index show]
    collection do
      get :index_owner
    end
  end
end

app/models/forest.rb
class Forest < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [
      [:address, 'A'],
      [:title, 'B'],
      [:description, 'C'],
      [:tree, 'D'],
      [:animals, 'D']
    ],
    using: {
      tsearch: { prefix: true }
    }

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :forest_reviews, dependent: :destroy
  has_many_attached :photos

  ANIMALS = %w(Lizards Toucans Kittens Rabbits Boars)
  TREES = %w(Mahagony Plywood Birch Pine)

  validates :title, :description, :address, :tree, :animals, :price, :size, presence: true
  validates :title, length: { in: 6..150 }
  validates :title, uniqueness: true
  validates :description, :address, length: { in: 6..600 }
  validates :price, numericality: { in: 15..250 }
  validates :size, numericality: { only_integer: true }
  validates :animals, presence: true, inclusion: { in: ANIMALS }
  validates :tree, presence: true, inclusion: { in: TREES }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # add inclusion to tree and animals
end

app/controllers/forests_controller.rb
require 'date'

class ForestsController < ApplicationController
  before_action :forest_find, only: %i[show edit update destroy]

  def index
    @forests = policy_scope(Forest)

    if params[:query].present?
      @forests = Forest.global_search(params[:query])
    else
      @forests = Forest.all
    end

    @markers = @forests.geocoded.map do |forest|
       {
         lat: forest.latitude,
         lng: forest.longitude,
         info_window: render_to_string(partial: "info_window", locals: { forest: forest }),
         image_url: helpers.asset_url("logo.png")
       }
    end

  end

  def index_owner
    @forests = Forest.where(user: current_user)
    authorize @forests
    @today = Date.today
  end

  def show
    authorize @forest
    @booking = Booking.new
  end

  def new
    @forest = Forest.new
    authorize @forest
  end

  def create
    @forest = Forest.new(forest_params)
    authorize @forest
    @forest.user = current_user
    if @forest.save
      redirect_to '/forests/index_owner'
    else
      render :new
    end
  end

  def edit
    authorize @forest
  end

  def update
    authorize @forest
    if @forest.update(forest_params)
      redirect_to forest_path(@forest)
    else
      render :edit
    end
  end

  def destroy
    authorize @forest
    if @forest.destroy
      redirect_to '/forests/index_owner'
    else
      redirect_to forest_path(@forest)
    end
  end

  private

  def forest_params
    params.require(:forest).permit(:title, :description, :address, :tree, :animals, :price, :size, photos: [])
  end

  def forest_find
    @forest = Forest.find(params[:id])
  end
end

app/views/forests/_form.html.erb
<div class="container">
  <div class="container-new-forest">
    <%= simple_form_for (@forest),
    wrapper: :floating_labels_form,
    wrapper_mappings: {
      select: :floating_labels_select
    }  do |f| %>
      <div class="form-text">The Shire 🧙</div>
        <%= f.input :title, placeholder: "test"  %>
      <div class="form-text">Inspire us with your magical forest ✨</div>
      <%= f.input :description, placeholder: "test" %>
      <div class="form-text">Where is the magic happening? 🧭</div>
      <%= f.input :address,placeholder: "test" %>
      <div class="form-inline">
          <div class="form-left">
            <div class="form-text">Where will we build the treehouse? 🌲</div>
            <%= f.input :tree, collection: Forest::TREES %>
            <div class="form-text">How big is it? 📏</div>
            <%= f.input :size, placeholder: "test" %>
          </div>
          <div class="form-right">
            <div class="form-text">Tell us more about the wildlife 🐼</div>
            <%= f.input :animals, collection: Forest::ANIMALS, placeholder: "test" %>
            <div class="form-text">What's the rate, mate? 🏷️</div>
            <%= f.input :price, placeholder: "test" %>
          </div>
      </div>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <div class="text-center">
        <%= f.submit class: 'btn submit-button'%>
      </div>
    <% end %>
  </div>
</div>

app/views/forests/_info_window.erb
<h2><%= forest.title %></h2>
<p><%= forest.address %></p>
<p><%= forest.price %> € per night</p>

app/views/forests/edit.html.erb
<%= render 'form', forest: @forest %>

app/views/forests/index.html.erb
<div class="wrap">

  <div class="cards-container">
    <% if @forests.any? %>
      <% if @forests.size == 1 %>
        <p><%=  @forests.size %> Result for <strong><%= (params[:query]) %></strong></p>
      <% else %>
        <p><%=  @forests.size %> Results for <strong><%= (params[:query]) %></strong></p>
      <% end %>
      <% @forests.each do |forest| %>
        <%= link_to forest_path(forest), data: { turbolinks: 'false' } do %>
          <div class="forest-card">
            <div class="card-image">
              <% if forest.photos.first %>
                <%= cl_image_tag forest.photos.first.key %>
              <% else %>
                <%= image_tag 'forests/forest1.jpg'%>
              <% end %>
            </div>
            <div class="card-infos">
              <h3><%= forest.title %></h3>
              <p><%= forest.description %></p>
              <p><%= forest.address %></p>
            </div>
            <div class="coeur-price">
              <% if forest.user.photo.key %>
                <%= cl_image_tag forest.user.photo.key, crop: :fill, class: 'avatar' %>
              <% else %>
                <%= image_tag 'gnome-avatar.jpg', class: 'avatar' %>
              <% end %>
              <p><%= forest.price.to_i %> € / night</p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <p>Sorry, we don't have any forest matching your search 😬</p>
    <% end %>


    <%# if policy(Forest).create? %>
      <%#= link_to 'Add a forest', new_forest_path %>
    <%# end %>

  </div>


    <div id='mapbox'
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

</div>

app/views/forests/index_owner.html.erb
<div class="d-flex wrapper align-items-start">
  <div class="nav flex-column nav-pills nav-lat" id="v-pills-tab" role="tablist" aria-orientation="vertical">
    <button class="nav-link <%= 'active' if params[:trip] %>" id="v-pills-home-tab" data-bs-toggle="pill" data-bs-target="#v-pills-home" type="button" role="tab" aria-controls="v-pills-home" aria-selected="true">
      <h1> <%= "Next Trip".pluralize(current_user.bookings.count) %></h1>
    </button>
    <button class="nav-link" id="v-pills-last-tab" data-bs-toggle="pill" data-bs-target="#v-pills-last" type="button" role="tab" aria-controls="v-pills-last" aria-selected="true">
      <h1> <%= "Last Trip".pluralize(current_user.bookings.count) %></h1>
    </button>
    <button class="nav-link <%= 'active' unless params[:message] || params[:trip] %>" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="false">
      <h1> <%= "My Forest".pluralize(@forests.length) %></h1>
    </button>
    <button class="nav-link" id="v-pills-messages-tab" data-bs-toggle="pill" data-bs-target="#v-pills-messages" type="button" role="tab" aria-controls="v-pills-messages" aria-selected="false">
      <h1>Notifications</h1>
    </button>
    <button class="nav-link <%= 'active' if params[:message] %>" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" role="tab" aria-controls="v-pills-settings" aria-selected="false">
      <h1>Messages</h1>
    </button>
  </div>

  <div class="tab-content dashboard-pages" id="v-pills-tabContent">
    <h1 class="welcome-back">Welcome Back <%= current_user.first_name %> !   🎉</h1>


    <div class="tab-pane fade <%= ' show active' if params[:trip] %>" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
       <h1> <%= "My Next Trip".pluralize(current_user.bookings.count) %></h1>
        <% if current_user.bookings.length == 0 %>
          <h2 class='mt-5'>No Forestreep booked yet!</h2>
          <div class="button-classic"><%= link_to 'Find your next Forestreep', forests_path %></div>
        <% else %>
          <div class="forests-cards">
            <% current_user.bookings.each do |booking| %>
              <% if booking.end_date > @today %>
                <div class="forest-card">
                  <div class="card-image">
                    <% if booking.forest.photos.first %>
                      <%= cl_image_tag booking.forest.photos.first.key %>
                    <% else %>
                      <%= image_tag 'forests/forest1.jpg'%>
                    <% end %>
                  </div>
                  <div class="card-infos-rental">
                    <div class="name-nbday">
                      <h3><%= booking.forest.title %></h3>
                      <p>(<%= (booking.end_date - booking.start_date).to_i.round  %> <%= "night".pluralize((booking.end_date - booking.start_date).to_i.round) %>)</p>
                    </div>
                    <p>● Check-in:  <%= booking.start_date.strftime("%A, %d %B %Y") %> </p>
                    <p>● Check-out: <%= booking.end_date.strftime("%A, %d %B %Y") %> </p>
                    <p class="address-card">In : <em><%= booking.forest.address %></em></p>
                  </div>
                  <div class="coeur-price-my-trips">
                    <div class="icons-fa-trip">
                      <%= link_to "/forests/#{booking.forest.id}" do %>
                        <i class="fas fa-eye"></i>
                      <% end %>
                      <%= link_to "/forests/#{booking.forest.id}/bookings/#{booking.id}", method: :delete, data: { confirm: "Are you sure to delete this reservation?" }  do %>
                        <i class="fas fa-trash-alt"></i>
                      <% end %>
                    </div>
                    <p>Total price : <%= (booking.forest.price * (booking.end_date - booking.start_date).to_i).round %> €</p>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
    </div>


    <div class="tab-pane fade" id="v-pills-last" role="tabpanel" aria-labelledby="v-pills-last-tab">
      <h1> <%= "My Last Trip".pluralize(current_user.bookings.count) %></h1>
        <% if current_user.bookings.length == 0 %>
          <h2 class='mt-5'>No ForesTreep booked yet!</h2>
          <div class="button-classic"><%= link_to 'Find your next Forestreep', forests_path %></div>
        <% else %>
          <div class="forests-cards">
            <% current_user.bookings.each do |booking| %>
              <% if booking.end_date < @today %>
                <div class="forest-card">
                  <div class="card-image">
                    <% if booking.forest.photos.first %>
                      <%= cl_image_tag booking.forest.photos.first.key %>
                    <% else %>
                      <%= image_tag 'forests/forest1.jpg'%>
                    <% end %>
                  </div>
                  <div class="card-infos-rental">
                    <div class="name-nbday">
                      <h3><%= booking.forest.title %></h3>
                      <p>(<%= (booking.end_date - booking.start_date).to_i.round  %> <%= "night".pluralize((booking.end_date - booking.start_date).to_i.round) %>)</p>
                    </div>
                    <p>● Check-in:  <%= booking.start_date.strftime("%A, %d %B %Y") %> </p>
                    <p>● Check-out: <%= booking.end_date.strftime("%A, %d %B %Y") %> </p>
                    <p class="address-card">In : <em><%= booking.forest.address %></em></p>
                  </div>
                  <div class="coeur-price-my-trips">
                    <div class="icons-fa-trip">
                      <%= link_to "/forests/#{booking.forest.id}" do %>
                        <i class="fas fa-eye"></i>
                      <% end %>
                      <%= link_to "/forests/#{booking.forest.id}/forest_reviews/new" do %>
                        <i class="fas fa-star"></i>
                      <% end %>
                    </div>
                    <p>Total price: <%= (booking.forest.price * (booking.end_date - booking.start_date).to_i).round %> €</p>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
    </div>

    <div class="tab-pane fade <%= 'show active' unless params[:message] || params[:trip] %>" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
       <h1> <%= "My Forest".pluralize(@forests.length) %></h1>
      <% if @forests.length == 0 %>
        <h2 class='mt-5'>You are not hosting any forest at the moment</h2>
        <div class="button-classic"><%= link_to 'Add your first rental forest', new_forest_path %></div>
      <% else %>
        <div class="forests-cards">

          <% @forests.each do |forest| %>

            <div class="forest-card">
              <div class="card-image">
                <% if forest.photos.first %>
                  <%= cl_image_tag forest.photos.first.key %>
                <% else %>
                  <%= image_tag 'forests/forest1.jpg'%>
                <% end %>
              </div>
              <div class="card-infos">
                <h3><%= forest.title %></h3>
                <p><%= forest.description %></p>
                <p>Location: <em><%= forest.address %></em></p>
              </div>
              <div class="coeur-price">
                <div class="icons-fa">
                  <%= link_to forest_path(forest) do %>
                    <i class="fas fa-eye"></i>
                  <% end %>
                  <%= link_to "/forests/#{forest.id}/edit" do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                  <%= link_to forest_path(forest), method: :delete, data: { confirm: "Are you sure?" }  do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                </div>
                <p><%= forest.price.to_i %> € / night</p>
              </div>
            </div>

          <% end %>

        </div>
      <% end %>
    </div>


    <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
      <h1>Notifications</h1>
        <h2 class='mt-5'>You don't have any notification at the moment</h2>
    </div>

    <div class="tab-pane fade <%= 'show active' if params[:message] %>" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
      <div class="container-messages">
        <%# <h1>Messages</h1> %>
      <%= render 'shared/chat' %>
      </div>
    </div>
  </div>
</div>

app/views/forests/new.html.erb
<%= render 'form', forest: @forest %>

app/views/forests/show.html.erb
<div class="forest-show-container col-8 offset-2">


  <div class="forest-header-show">
    <div>
      <h1><%= @forest.title.capitalize %></h1>
    </div>
   <div class="forest-header-show-details">
      <h6><%= @forest.address %></h6>
    </div>
  </div>


  <% if @forest.photos.size < 2 %>
    <div class="show-forest-one">
      <div class="row-forest-one">
        <% @forest.photos.each do |photo| %>
          <div class="forest-photo-one">
            <%= cl_image_tag photo.key %>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="show-forest-photos">
      <h1><i class="fas fa-arrow-left"></i>   Swipe   <i class="fas fa-arrow-right"></i></h1>
      <div class="row-forest-photos">
        <% @forest.photos.each do |photo| %>
          <div class="forest-photo">
            <%= cl_image_tag photo.key %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="details-booking-container">
    <div class="forest-details">
      <div class="forest-details-infos">
        <div>
          <h3>Entire forest ● Hosted by <%= @forest.user.first_name %> <%= @forest.user.last_name %></h3>
          <p>Type of trees : <%= @forest.tree %> ● Type of animals : <%= @forest.animals %> ● Forest size : <%= @forest.size %> m²</p>
        </div>
        <div class='user-photo-avatar'>
          <% if @forest.user.photo.key %>
            <%= cl_image_tag @forest.user.photo.key, crop: :fill, class: 'avatar' %>
          <% else %>
            <%= image_tag 'gnome-avatar.jpg', class: 'avatar' %>
          <% end %>
        </div>
      </div>

      <div class="infos">
        <h3><%= @forest.user.first_name %> <%= @forest.user.last_name %> is a Superhost</h3>
        <p>Superhosts are experienced gnomes, who are commited to provinding great stays for their guests.</p>
        <h3>Great forest</h3>
        <p>100% of recent guests gave the forest a 5-star rating.</p>
        <h3>Free cancellation up to 24 hours prior</h3>
      </div>

      <div class="forest-description">
        <h3>More details</h3>
        <p> <%= @forest.description %></p>
      </div>

      <div class="offers">
        <h3>This forest's perks</h3>
        <div class="pictos-offers">
          <p>🔥 Campfire</p>
          <p>👨‍🍳 Potion making</p>
          <p>🎯 Dwarf tossing</p>
          <p>🚲 Biking</p>
          <p>🍄 Mushroom picking</p>
          <p>🧺 Picnic</p>
          <p>⛺ Hut building</p>
          <p>🌲 Tree climbing</p>
        </div>
      </div>

      <div class="forest-reviews">
          <h3>Reviews</h3>
          <% @forest.forest_reviews.each do |review| %>
            <div class="review-card">
              <div class="name-rating">
                <div class="user-review-infos">
                  <% if review.user.photo.key %>
                    <%= cl_image_tag review.user.photo.key, crop: :fill, class: 'avatar' %>
                  <% else %>
                    <%= image_tag 'gnome-avatar.jpg', class: 'avatar' %>
                  <% end %>
                  <p class="fullname"><%= review.user.first_name %> <%= review.user.last_name %></p>
                </div>
                <p class="stars"><%= "★" * review.rating %><%= "☆" * (5 - review.rating) %></p>
              </div>
              <div class="comment">
                <p><%= review.comment %></p>
              </div>
            </div>
          <% end %>
      </div>
    </div>

    <div id="booking-card" class="forest-booking-card">
      <div class='price-card-booking'>
        <h3> <span id="price"><%= @forest.price.to_i %></span> € per night </h3>
      </div>
      <br>
      <div class="booking-title">
        <h3>Booking</h3>
      </div>

      <%= simple_form_for [@forest, @booking],
        data: {controller: "total-price", action: "change->total-price#totalPrice"},
        wrapper: :floating_labels_form,
        wrapper_mappings: {
          select: :floating_labels_select
        }  do |f| %>
          <%= f.error_notification %>
          <%= f.input :start_date, as: :string, required: true, input_html: {id: "booking_start_date"} %>
          <%= f.input :end_date, as: :string, required: true, input_html: {id: "booking_end_date"} %>
          <div class="buttons">
            <%= f.button :button, 'Reset dates', :type => 'reset', :class => 'btn btn-reset' %>
            <p>Total price: <span data-total-price-target="totalprice">0</span> €</p>
            <%= f.submit "Submit booking", class: "button-booking" %>
          </div>
      <% end %>
    </div>
  </div>
  <%= link_to "Back to results page", '/forests', class: 'back-btn m-3', data: { turbolinks: 'false' } %>
</div>